defaults:
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

hydra:
  run:
    dir: .
  output_subdir: null

# 事前学習用の元設定ファイル
config_path: configs/pretrain_language_model.yaml

trainer:
  accelerator: auto
  devices: auto
  precision: 32
  log_every_n_steps: 50
  max_epochs: null  # null の場合は元設定(training_epochs)を使用

wandb:
  enable: true
  project: abinet-kuzushiji-language
  entity: null
  run_name: null
  mode: online
  tags: []
